version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: junit:junit
    versions:
    - 4.13.2
